### ISSUE TITLE
hi, I try to run CgvsPhoto, but I got an error

### ISSUE THREAD

**Issue by NemoCpp** [NicoRahm/CGvsPhoto#2]
Restore weight from previous session ? (y/N) : N
   train ...
Traceback (most recent call last):
  File "test_pipeline.py", line 18, in <module>
    nb_validation_batch = 40,
  File "/home/ubuntu/anaconda2/envs/pyannote/lib/python3.5/site-packages/CGvsPhoto/model.py", line 632, in train
    show_filters = show_filters)
  File "/home/ubuntu/anaconda2/envs/pyannote/lib/python3.5/site-packages/CGvsPhoto/model.py", line 496, in validation_testing
    random_rotate = True)
  File "/home/ubuntu/anaconda2/envs/pyannote/lib/python3.5/site-packages/CGvsPhoto/image_loader.py", line 405, in get_batch_validation
    data = self.get_next_validation(crop, self.rand_crop, random_flip_flop,random_rotate, verbose=False)
  File "/home/ubuntu/anaconda2/envs/pyannote/lib/python3.5/site-packages/CGvsPhoto/image_loader.py", line 389, in get_next_validation
    image = image.reshape(self.size, self.size, self.nb_channels)
ValueError: cannot reshape array of size 30000 into shape (100,100,1)

**Comment by NicoRahm** [comment]
Hi, thank you for reporting this issue. 
Did you install the package directly with pip? Because I think it was not up-to-date. If you try to update the package now it should work better. 
If not please let me know what is the dimension and type of images you are using (I only tried with JPEG so far) and if to what value you set the parameter 'only_green' in the Model definition.
